<?php

if(function_exists("register_field_group"))
{
    if(function_exists("register_field_group"))
    {
        register_field_group(array (
            'id' => 'acf_admin-player-profile',
            'title' => 'ADMIN - Player Profile',
            'fields' => array (
                array (
                    'key' => 'field_5353e2a7c221e',
                    'label' => 'User profile link',
                    'name' => 'user_id',
                    'type' => 'user',
                    'role' => array (
                        0 => 'all',
                    ),
                    'field_type' => 'select',
                    'allow_null' => 1,
                ),
                array (
                    'key' => 'field_5367966ccb823',
                    'label' => 'PA Stats player ID',
                    'name' => 'pastats_player_id',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_53e0156cac47e',
                    'label' => 'Player is caster',
                    'name' => 'player_is_caster',
                    'type' => 'true_false',
                    'instructions' => 'When check will enable user to add a text box for commentary box on live page',
                    'message' => '',
                    'default_value' => 0,
                ),
                array (
                    'key' => 'field_53e614b3c6254',
                    'label' => 'Uber ID',
                    'name' => 'uberid',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'player',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                    array (
                        'param' => 'user_type',
                        'operator' => '==',
                        'value' => 'administrator',
                        'order_no' => 1,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'default',
                'hide_on_screen' => array (
                ),
            ),
            'menu_order' => 0,
        ));
    }

    register_field_group(array (
        'id' => 'acf_match-meta',
        'title' => 'Match Meta',
        'fields' => array (
            array (
                'key' => 'field_53557b83039b7',
                'label' => 'Challonge Match ID',
                'name' => 'challonge_match_id',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_53557b9b039b8',
                'label' => 'Challonge Tournament ID',
                'name' => 'challonge_tournament_id',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_53557ba6039b9',
                'label' => 'PA Stats match ID',
                'name' => 'pa_stats_match_id',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_53557bca039ba',
                'label' => 'PA Stats start',
                'name' => 'pa_stats_start',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_535d564f29924',
                'label' => 'PA Stats Stop',
                'name' => 'pa_stats_stop',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_537136ab23850',
                'label' => 'Match Round',
                'name' => 'match_round',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_537136c123851',
                'label' => 'Twitch',
                'name' => 'twitch',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_537136d523852',
                'label' => 'Favourite',
                'name' => 'favourite',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'match',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_notification',
        'title' => 'Notification',
        'fields' => array (
            array (
                'key' => 'field_5377e4c0a7eeb',
                'label' => 'Notification Actions',
                'name' => 'notification_actions',
                'type' => 'select',
                'choices' => array (
                    'tournament_signup_Active' => 'Tournament Signup Not Reserve',
                    'tournament_signup_Reserve' => 'Tournament Signup Reserve',
                    'player_missing_pa_stats_id' => 'Player Missing PA Stats ID',
                    'tournament_2_day_notice' => 'Tournament 2 day notice',
                    'tournament_wrap_up' => 'Tournament Wrap Up',
                ),
                'default_value' => '',
                'allow_null' => 1,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'notification',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    if(function_exists("register_field_group"))
    {
        register_field_group(array (
            'id' => 'acf_player-profile',
            'title' => 'Player Profile',
            'fields' => array (
                array (
                    'key' => 'field_5353e38c75c10',
                    'label' => 'Your Email',
                    'name' => 'player_email',
                    'type' => 'email',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array (
                    'key' => 'field_5353e3a175c11',
                    'label' => 'Profile text',
                    'name' => 'profile_text',
                    'type' => 'wysiwyg',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'yes',
                ),
                array (
                    'key' => 'field_53e015b0fabdc',
                    'label' => 'Commentary Profile',
                    'name' => 'commentary_profile',
                    'type' => 'textarea',
                    'instructions' => 'Will appear on a tournament in progress page when your are a match Commentator. (125 Character Limit)',
                    'conditional_logic' => array (
                        'status' => 1,
                        'rules' => array (
                            array (
                                'field' => 'null',
                                'operator' => '==',
                                'value' => '',
                            ),
                        ),
                        'allorany' => 'all',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => 125,
                    'rows' => '',
                    'formatting' => 'br',
                ),
                array (
                    'key' => 'field_53e614f15669e',
                    'label' => 'Country',
                    'name' => 'country',
                    'type' => 'select',
                    'choices' => array (
                        'GB' => 'United Kingdom',
                        'US' => 'United States',
                        'AF' => 'Afghanistan',
                        'AL' => 'Albania',
                        'DZ' => 'Algeria',
                        'AS' => 'American Samoa',
                        'AD' => 'Andorra',
                        'AO' => 'Angola',
                        'AI' => 'Anguilla',
                        'AQ' => 'Antarctica',
                        'AG' => 'Antigua And Barbuda',
                        'AR' => 'Argentina',
                        'AM' => 'Armenia',
                        'AW' => 'Aruba',
                        'AU' => 'Australia',
                        'AT' => 'Austria',
                        'AZ' => 'Azerbaijan',
                        'BS' => 'Bahamas',
                        'BH' => 'Bahrain',
                        'BD' => 'Bangladesh',
                        'BB' => 'Barbados',
                        'BY' => 'Belarus',
                        'BE' => 'Belgium',
                        'BZ' => 'Belize',
                        'BJ' => 'Benin',
                        'BM' => 'Bermuda',
                        'BT' => 'Bhutan',
                        'BO' => 'Bolivia',
                        'BA' => 'Bosnia And Herzegowina',
                        'BW' => 'Botswana',
                        'BV' => 'Bouvet Island',
                        'BR' => 'Brazil',
                        'IO' => 'British Indian Ocean Territory',
                        'BN' => 'Brunei Darussalam',
                        'BG' => 'Bulgaria',
                        'BF' => 'Burkina Faso',
                        'BI' => 'Burundi',
                        'KH' => 'Cambodia',
                        'CM' => 'Cameroon',
                        'CA' => 'Canada',
                        'CV' => 'Cape Verde',
                        'KY' => 'Cayman Islands',
                        'CF' => 'Central African Republic',
                        'TD' => 'Chad',
                        'CL' => 'Chile',
                        'CN' => 'China',
                        'CX' => 'Christmas Island',
                        'CC' => 'Cocos (Keeling) Islands',
                        'CO' => 'Colombia',
                        'KM' => 'Comoros',
                        'CG' => 'Congo',
                        'CD' => 'Congo, The Democratic Republic Of The',
                        'CK' => 'Cook Islands',
                        'CR' => 'Costa Rica',
                        'CI' => 'Cote D\'Ivoire',
                        'HR' => 'Croatia (Local Name: Hrvatska)',
                        'CU' => 'Cuba',
                        'CY' => 'Cyprus',
                        'CZ' => 'Czech Republic',
                        'DK' => 'Denmark',
                        'DJ' => 'Djibouti',
                        'DM' => 'Dominica',
                        'DO' => 'Dominican Republic',
                        'TP' => 'East Timor',
                        'EC' => 'Ecuador',
                        'EG' => 'Egypt',
                        'SV' => 'El Salvador',
                        'GQ' => 'Equatorial Guinea',
                        'ER' => 'Eritrea',
                        'EE' => 'Estonia',
                        'ET' => 'Ethiopia',
                        'FK' => 'Falkland Islands (Malvinas)',
                        'FO' => 'Faroe Islands',
                        'FJ' => 'Fiji',
                        'FI' => 'Finland',
                        'FR' => 'France',
                        'FX' => 'France, Metropolitan',
                        'GF' => 'French Guiana',
                        'PF' => 'French Polynesia',
                        'TF' => 'French Southern Territories',
                        'GA' => 'Gabon',
                        'GM' => 'Gambia',
                        'GE' => 'Georgia',
                        'DE' => 'Germany',
                        'GH' => 'Ghana',
                        'GI' => 'Gibraltar',
                        'GR' => 'Greece',
                        'GL' => 'Greenland',
                        'GD' => 'Grenada',
                        'GP' => 'Guadeloupe',
                        'GU' => 'Guam',
                        'GT' => 'Guatemala',
                        'GN' => 'Guinea',
                        'GW' => 'Guinea-Bissau',
                        'GY' => 'Guyana',
                        'HT' => 'Haiti',
                        'HM' => 'Heard And Mc Donald Islands',
                        'VA' => 'Holy See (Vatican City State)',
                        'HN' => 'Honduras',
                        'HK' => 'Hong Kong',
                        'HU' => 'Hungary',
                        'IS' => 'Iceland',
                        'IN' => 'India',
                        'ID' => 'Indonesia',
                        'IR' => 'Iran (Islamic Republic Of)',
                        'IQ' => 'Iraq',
                        'IE' => 'Ireland',
                        'IL' => 'Israel',
                        'IT' => 'Italy',
                        'JM' => 'Jamaica',
                        'JP' => 'Japan',
                        'JO' => 'Jordan',
                        'KZ' => 'Kazakhstan',
                        'KE' => 'Kenya',
                        'KI' => 'Kiribati',
                        'KP' => 'Korea, Democratic People\'s Republic Of',
                        'KR' => 'Korea, Republic Of',
                        'KW' => 'Kuwait',
                        'KG' => 'Kyrgyzstan',
                        'LA' => 'Lao People\'s Democratic Republic',
                        'LV' => 'Latvia',
                        'LB' => 'Lebanon',
                        'LS' => 'Lesotho',
                        'LR' => 'Liberia',
                        'LY' => 'Libyan Arab Jamahiriya',
                        'LI' => 'Liechtenstein',
                        'LT' => 'Lithuania',
                        'LU' => 'Luxembourg',
                        'MO' => 'Macau',
                        'MK' => 'Macedonia, Former Yugoslav Republic Of',
                        'MG' => 'Madagascar',
                        'MW' => 'Malawi',
                        'MY' => 'Malaysia',
                        'MV' => 'Maldives',
                        'ML' => 'Mali',
                        'MT' => 'Malta',
                        'MH' => 'Marshall Islands',
                        'MQ' => 'Martinique',
                        'MR' => 'Mauritania',
                        'MU' => 'Mauritius',
                        'YT' => 'Mayotte',
                        'MX' => 'Mexico',
                        'FM' => 'Micronesia, Federated States Of',
                        'MD' => 'Moldova, Republic Of',
                        'MC' => 'Monaco',
                        'MN' => 'Mongolia',
                        'MS' => 'Montserrat',
                        'MA' => 'Morocco',
                        'MZ' => 'Mozambique',
                        'MM' => 'Myanmar',
                        'NA' => 'Namibia',
                        'NR' => 'Nauru',
                        'NP' => 'Nepal',
                        'NL' => 'Netherlands',
                        'AN' => 'Netherlands Antilles',
                        'NC' => 'New Caledonia',
                        'NZ' => 'New Zealand',
                        'NI' => 'Nicaragua',
                        'NE' => 'Niger',
                        'NG' => 'Nigeria',
                        'NU' => 'Niue',
                        'NF' => 'Norfolk Island',
                        'MP' => 'Northern Mariana Islands',
                        'NO' => 'Norway',
                        'OM' => 'Oman',
                        'PK' => 'Pakistan',
                        'PW' => 'Palau',
                        'PA' => 'Panama',
                        'PG' => 'Papua New Guinea',
                        'PY' => 'Paraguay',
                        'PE' => 'Peru',
                        'PH' => 'Philippines',
                        'PN' => 'Pitcairn',
                        'PL' => 'Poland',
                        'PT' => 'Portugal',
                        'PR' => 'Puerto Rico',
                        'QA' => 'Qatar',
                        'RE' => 'Reunion',
                        'RO' => 'Romania',
                        'RU' => 'Russian Federation',
                        'RW' => 'Rwanda',
                        'KN' => 'Saint Kitts And Nevis',
                        'LC' => 'Saint Lucia',
                        'VC' => 'Saint Vincent And The Grenadines',
                        'WS' => 'Samoa',
                        'SM' => 'San Marino',
                        'ST' => 'Sao Tome And Principe',
                        'SA' => 'Saudi Arabia',
                        'SN' => 'Senegal',
                        'SC' => 'Seychelles',
                        'SL' => 'Sierra Leone',
                        'SG' => 'Singapore',
                        'SK' => 'Slovakia (Slovak Republic)',
                        'SI' => 'Slovenia',
                        'SB' => 'Solomon Islands',
                        'SO' => 'Somalia',
                        'ZA' => 'South Africa',
                        'GS' => 'South Georgia, South Sandwich Islands',
                        'ES' => 'Spain',
                        'LK' => 'Sri Lanka',
                        'SH' => 'St. Helena',
                        'PM' => 'St. Pierre And Miquelon',
                        'SD' => 'Sudan',
                        'SR' => 'Suriname',
                        'SJ' => 'Svalbard And Jan Mayen Islands',
                        'SZ' => 'Swaziland',
                        'SE' => 'Sweden',
                        'CH' => 'Switzerland',
                        'SY' => 'Syrian Arab Republic',
                        'TW' => 'Taiwan',
                        'TJ' => 'Tajikistan',
                        'TZ' => 'Tanzania, United Republic Of',
                        'TH' => 'Thailand',
                        'TG' => 'Togo',
                        'TK' => 'Tokelau',
                        'TO' => 'Tonga',
                        'TT' => 'Trinidad And Tobago',
                        'TN' => 'Tunisia',
                        'TR' => 'Turkey',
                        'TM' => 'Turkmenistan',
                        'TC' => 'Turks And Caicos Islands',
                        'TV' => 'Tuvalu',
                        'UG' => 'Uganda',
                        'UA' => 'Ukraine',
                        'AE' => 'United Arab Emirates',
                        'UM' => 'United States Minor Outlying Islands',
                        'UY' => 'Uruguay',
                        'UZ' => 'Uzbekistan',
                        'VU' => 'Vanuatu',
                        'VE' => 'Venezuela',
                        'VN' => 'Viet Nam',
                        'VG' => 'Virgin Islands (British)',
                        'VI' => 'Virgin Islands (U.S.)',
                        'WF' => 'Wallis And Futuna Islands',
                        'EH' => 'Western Sahara',
                        'YE' => 'Yemen',
                        'YU' => 'Yugoslavia',
                        'ZM' => 'Zambia',
                        'ZW' => 'Zimbabwe',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_53e61cf49e616',
                    'label' => 'Clan',
                    'name' => 'clan',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'player',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'default',
                'hide_on_screen' => array (
                ),
            ),
            'menu_order' => 0,
        ));
    }
    register_field_group(array (
        'id' => 'acf_pltm-signatures',
        'title' => 'PLTM Signatures',
        'fields' => array (
            array (
                'key' => 'field_53700be82ece6',
                'label' => 'Site Signatures',
                'name' => 'site_signatures',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_53701077fb232',
                        'label' => 'Signature image',
                        'name' => 'signature_image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'object',
                        'preview_size' => 'guide-banner',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_537010fafb233',
                        'label' => 'Keyword',
                        'name' => 'keyword',
                        'type' => 'text',
                        'instructions' => 'Random is a reserved word, for example http://dev.exodusesports.com/signature/{keyword}/signature.png',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Signature',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-pltm-signatures',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_theme-options-2',
        'title' => 'Theme Options',
        'fields' => array (
            array (
                'key' => 'field_531a656544f48',
                'label' => 'Standard tournament signup form',
                'name' => 'standard_tournament_signup_form',
                'type' => 'select',
                'choices' => array (
                    6 => 'Community Cup',
                    2 => 'Contact',
                    5 => 'Livestream - Survey',
                    16 => 'Newsletter',
                    3 => 'PreLim Feedback',
                    7 => 'Project Genesis - Invitation',
                    9 => 'Project Genesis - Map Review',
                    4 => 'Showdown - Survey',
                    11 => 'Survey - Community Cup',
                    13 => 'Survey - Community Cup - Copy 1',
                    15 => 'Survey - Players',
                    14 => 'Survey - Viewers',
                    10 => 'test',
                    12 => 'test3',
                    1 => 'Tournament Signup',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5338622f6a7b4',
                'label' => 'Challonge API',
                'name' => 'challonge_api',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_tournament-in-progress',
        'title' => 'Tournament In Progress',
        'fields' => array (
            array (
                'key' => 'field_53d436ea652a7',
                'label' => 'Stream',
                'name' => 'stream',
                'type' => 'repeater',
                'instructions' => 'When changes are made to this page, they will happen in realtime across all viewers',
                'sub_fields' => array (
                    array (
                        'key' => 'field_53d43712652a8',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                        'instructions' => 'If more than 2 steams are set then this name will be used in the tabs',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_53d4373d652a9',
                        'label' => 'Commentators',
                        'name' => 'commentators',
                        'type' => 'repeater',
                        'instructions' => 'Select a commentator this box will appear at the top of the page',
                        'required' => 1,
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_53d43757652aa',
                                'label' => 'Select a commentator',
                                'name' => 'select_a_commentator',
                                'type' => 'user',
                                'required' => 1,
                                'column_width' => '',
                                'role' => array (
                                    0 => 'all',
                                ),
                                'field_type' => 'select',
                                'allow_null' => 0,
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 2,
                        'layout' => 'table',
                        'button_label' => 'Add Commentator',
                    ),
                    array (
                        'key' => 'field_53d437b6652ab',
                        'label' => 'Twitch Channel Name',
                        'name' => 'twitch_channel_name',
                        'type' => 'text',
                        'instructions' => 'Name of the twitch channel to use',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_53d43872652ad',
                        'label' => 'Large Content Type',
                        'name' => 'large_content_type',
                        'type' => 'flexible_content',
                        'instructions' => 'Content to be displayed under the twitch stream, If no Small content type has been added then this will be full width.',
                        'column_width' => '',
                        'layouts' => array (
                            array (
                                'label' => 'Match',
                                'name' => 'match',
                                'display' => 'row',
                                'min' => '',
                                'max' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_53d4388b652ae',
                                        'label' => 'Select a match to show',
                                        'name' => 'select_a_match_to_show',
                                        'type' => 'post_object',
                                        'required' => 1,
                                        'column_width' => '',
                                        'post_type' => array (
                                            0 => 'match',
                                        ),
                                        'taxonomy' => array (
                                            0 => 'all',
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                    array (
                                        'key' => 'field_53d438af652af',
                                        'label' => 'Show winner poll',
                                        'name' => 'show_winner_poll',
                                        'type' => 'true_false',
                                        'instructions' => 'Will show a realtime poll for the match winner',
                                        'required' => 1,
                                        'column_width' => '',
                                        'message' => '',
                                        'default_value' => 1,
                                    ),
                                ),
                            ),
                            array (
                                'label' => 'Poll',
                                'name' => 'poll',
                                'display' => 'row',
                                'min' => '',
                                'max' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_53d438f8652b2',
                                        'label' => 'Poll Type',
                                        'name' => 'poll_type',
                                        'type' => 'select',
                                        'instructions' => 'Not in use',
                                        'column_width' => '',
                                        'choices' => array (
                                        ),
                                        'default_value' => '',
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                    ),
                                ),
                            ),
                            array (
                                'label' => 'Advert',
                                'name' => 'advert',
                                'display' => 'row',
                                'min' => '',
                                'max' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_53d4394a652b4',
                                        'label' => 'Advert image',
                                        'name' => 'advert_image',
                                        'type' => 'image',
                                        'column_width' => '',
                                        'save_format' => 'object',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                    ),
                                    array (
                                        'key' => 'field_53d43961652b5',
                                        'label' => 'Link to',
                                        'name' => 'link_to',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'button_label' => 'Add Content',
                        'min' => 0,
                        'max' => 1,
                    ),
                    array (
                        'key' => 'field_53d43da7863c3',
                        'label' => 'Small Content Type',
                        'name' => 'small_content_type',
                        'type' => 'flexible_content',
                        'instructions' => 'Under the twitch chat when.',
                        'column_width' => '',
                        'layouts' => array (
                            array (
                                'label' => 'Guest analyst',
                                'name' => 'guest_analyst',
                                'display' => 'row',
                                'min' => '',
                                'max' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_53d43df4863c4',
                                        'label' => 'Select analyst',
                                        'name' => 'select_analyst',
                                        'type' => 'user',
                                        'column_width' => '',
                                        'role' => array (
                                            0 => 'all',
                                        ),
                                        'field_type' => 'select',
                                        'allow_null' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'button_label' => 'Add Small content',
                        'min' => '',
                        'max' => 1,
                    ),
                    array (
                        'key' => 'field_53d43c2707b05',
                        'label' => 'Show match Listing',
                        'name' => 'show_match_listing',
                        'type' => 'true_false',
                        'column_width' => '',
                        'message' => '',
                        'default_value' => 1,
                    ),
                    array (
                        'key' => 'field_53dfed391d1d6',
                        'label' => 'Tournament Match Listing',
                        'name' => 'tournament_match_listing',
                        'type' => 'post_object',
                        'column_width' => '',
                        'post_type' => array (
                            0 => 'tournament',
                        ),
                        'taxonomy' => array (
                            0 => 'all',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Stream',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-tournament-in-progress-2.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'author',
                7 => 'format',
                8 => 'featured_image',
                9 => 'categories',
                10 => 'tags',
                11 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    if(function_exists("register_field_group"))
    {
        register_field_group(array (
            'id' => 'acf_tournament-meta',
            'title' => 'Tournament Meta',
            'fields' => array (
                array (
                    'key' => 'field_531a3508690d8',
                    'label' => 'Tournament Meta',
                    'name' => '',
                    'type' => 'tab',
                ),
                array (
                    'key' => 'field_536fa73ccaa06',
                    'label' => 'Tournament Status',
                    'name' => 'tournament_status',
                    'type' => 'select',
                    'required' => 1,
                    'choices' => array (
                        0 => 'Signup',
                        1 => 'In Progress',
                        2 => 'Cancelled',
                        3 => 'Finished',
                        4 => 'Preparation',
                    ),
                    'default_value' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_531a31bfb8693',
                    'label' => 'Run Date',
                    'name' => 'run_date',
                    'type' => 'date_picker',
                    'date_format' => 'yymmdd',
                    'display_format' => 'dd/mm/yy',
                    'first_day' => 1,
                ),
                array (
                    'key' => 'field_531a31ddb8694',
                    'label' => 'Run time',
                    'name' => 'run_time',
                    'type' => 'text',
                    'instructions' => 'Please enter in 01:00 format with :',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_531a31ffb8695',
                    'label' => 'Prize Tiers',
                    'name' => 'prize_tiers',
                    'type' => 'repeater',
                    'sub_fields' => array (
                        array (
                            'key' => 'field_531a3216b8696',
                            'label' => 'Place',
                            'name' => 'place',
                            'type' => 'text',
                            'column_width' => '',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                        ),
                        array (
                            'key' => 'field_531a3235b8697',
                            'label' => 'Prize',
                            'name' => 'prize',
                            'type' => 'text',
                            'column_width' => '',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                        ),
                    ),
                    'row_min' => '',
                    'row_limit' => '',
                    'layout' => 'table',
                    'button_label' => 'Add Row',
                ),
                array (
                    'key' => 'field_531a366dbeaf6',
                    'label' => 'Rounds',
                    'name' => 'rounds',
                    'type' => 'number',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => '',
                    'step' => '',
                ),
                array (
                    'key' => 'field_531a377136494',
                    'label' => 'Slots',
                    'name' => 'slots',
                    'type' => 'number',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => '',
                    'step' => '',
                ),
                array (
                    'key' => 'field_5376853ac289a',
                    'label' => 'Reserve slots',
                    'name' => 'reserve_slots',
                    'type' => 'number',
                    'default_value' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array (
                    'key' => 'field_53226662e5c75',
                    'label' => 'Tournament Type',
                    'name' => 'tournament_type',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_531a32947c201',
                    'label' => 'Brackets Link',
                    'name' => 'brackets',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_531a34d9a5387',
                    'label' => 'Forum Link',
                    'name' => 'forum_link',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_531a32dd7c203',
                    'label' => 'IRC',
                    'name' => 'irc',
                    'type' => 'text',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_531a33e5a5380',
                    'label' => 'Tournament Rules & Requirements and Other',
                    'name' => '',
                    'type' => 'tab',
                ),
                array (
                    'key' => 'field_531a3400a5381',
                    'label' => 'Requirements',
                    'name' => 'requirements',
                    'type' => 'wysiwyg',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'yes',
                ),
                array (
                    'key' => 'field_531a3436a5384',
                    'label' => 'Existing Requirements',
                    'name' => 'existing_requirements',
                    'type' => 'post_object',
                    'post_type' => array (
                        0 => 'page',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_531a341ba5382',
                    'label' => 'Rules',
                    'name' => 'rules',
                    'type' => 'wysiwyg',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'yes',
                ),
                array (
                    'key' => 'field_531a3481a5385',
                    'label' => 'Existing Rules',
                    'name' => 'existing_rules',
                    'type' => 'post_object',
                    'post_type' => array (
                        0 => 'page',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_531a3428a5383',
                    'label' => 'Other',
                    'name' => 'other',
                    'type' => 'wysiwyg',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'yes',
                ),
                array (
                    'key' => 'field_531a348fa5386',
                    'label' => 'Existing Other',
                    'name' => 'existing_rules',
                    'type' => 'post_object',
                    'post_type' => array (
                        0 => 'page',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_531a3540ca568',
                    'label' => 'Tournament Setup',
                    'name' => '',
                    'type' => 'tab',
                ),
                array (
                    'key' => 'field_531e5feaf3700',
                    'label' => 'Signup Intro Text',
                    'name' => 'signup_intro_text',
                    'type' => 'wysiwyg',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'yes',
                ),
                array (
                    'key' => 'field_531a329d7c202',
                    'label' => 'Signup Form',
                    'name' => 'signup_form',
                    'type' => 'select',
                    'instructions' => 'Will default to the system default signup form, unless a new form is selected here.',
                    'choices' => array (
                        6 => 'Community Cup',
                        2 => 'Contact',
                        5 => 'Livestream - Survey',
                        16 => 'Newsletter',
                        3 => 'PreLim Feedback',
                        7 => 'Project Genesis - Invitation',
                        9 => 'Project Genesis - Map Review',
                        4 => 'Showdown - Survey',
                        11 => 'Survey - Community Cup',
                        13 => 'Survey - Community Cup - Copy 1',
                        15 => 'Survey - Players',
                        14 => 'Survey - Viewers',
                        10 => 'test',
                        12 => 'test3',
                        1 => 'Tournament Signup',
                    ),
                    'default_value' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_532263dad2da7',
                    'label' => 'Signup Closed',
                    'name' => 'signup_closed',
                    'type' => 'true_false',
                    'instructions' => 'If you want to close the tournament signups for what ever reason tick this box',
                    'message' => '',
                    'default_value' => 0,
                ),
                array (
                    'key' => 'field_533864885ce19',
                    'label' => 'Challonge Tournament Link',
                    'name' => 'challonge_tournament_link',
                    'type' => 'select',
                    'instructions' => 'Select a tournament from the challonge DB, user will be inserted into selected tournament on signup.',
                    'choices' => array (
                        0 => 'Select Tournament',
                        1 => 'Custom Tournament ID',
                        1037783 => 'testtesttesttest 3',
                        981970 => 'Community Cup',
                        950890 => 'test',
                        988953 => 'test test',
                        922929 => 'supernovashowdown',
                        948036 => 'prelim',
                        948029 => 'prelimtest',
                    ),
                    'default_value' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_5338825672b61',
                    'label' => 'Custom tournament id',
                    'name' => 'custom_tournament_id',
                    'type' => 'text',
                    'conditional_logic' => array (
                        'status' => 1,
                        'rules' => array (
                            array (
                                'field' => 'field_533864885ce19',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                        'allorany' => 'all',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_53e92bc5ed541',
                    'label' => 'Twitch',
                    'name' => 'twitch',
                    'type' => 'text',
                    'instructions' => 'Twitch channels this is to be streamed on, just the name, not the url, comma separated is acceptable for multi stream tournaments',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'tournament',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'default',
                'hide_on_screen' => array (
                ),
            ),
            'menu_order' => 0,
        ));
    }
    register_field_group(array (
        'id' => 'acf_user-profile',
        'title' => 'User profile',
        'fields' => array (
            array (
                'key' => 'field_53226b3245ed1',
                'label' => 'Twitch url',
                'name' => 'twitch_url',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_53679971635a7',
                'label' => 'Twitter url',
                'name' => 'twitter_url',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5367998a635a8',
                'label' => 'Youtube url',
                'name' => 'youtube_url',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5367a4aa9d038',
                'label' => 'Your Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => 'Abusing this will result in site staff choosing a title for you.',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => 15,
            ),
            array (
                'key' => 'field_53691d51c2f4a',
                'label' => 'Twitch Username',
                'name' => 'twitch_username',
                'type' => 'text',
                'instructions' => 'Twitch username and URL MUST be filled in if you want the site to let a viewer know when your steaming.',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_user',
                    'operator' => '==',
                    'value' => 'all',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
}
